// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/analysis/sparc-galaxy-rotation-curves": {
    params: {};
  };
  "/analysis/solar-system": {
    params: {};
  };
  "/preprint/a-curvature-response-model-for-weak-field-gravity": {
    params: {};
  };
  "/non-trivial-mars-bars": {
    params: {};
  };
  "/notes/quantum-gravity-phase-resolution": {
    params: {};
  };
  "/notes/natural-mathematics-bell-toy": {
    params: {};
  };
  "/notes/regime-gate": {
    params: {};
  };
  "/notes/evaluation-protocol-for-progress-state-regime": {
    params: {};
  };
  "/notes/switching-quadratic-atlas-diagnostics": {
    params: {};
  };
  "/toy-galaxy": {
    params: {};
  };
  "/gate": {
    params: {};
  };
  "/rh": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/analysis/sparc-galaxy-rotation-curves" | "/analysis/solar-system" | "/preprint/a-curvature-response-model-for-weak-field-gravity" | "/non-trivial-mars-bars" | "/notes/quantum-gravity-phase-resolution" | "/notes/natural-mathematics-bell-toy" | "/notes/regime-gate" | "/notes/evaluation-protocol-for-progress-state-regime" | "/notes/switching-quadratic-atlas-diagnostics" | "/toy-galaxy" | "/gate" | "/rh";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/AnalysisSparc.tsx": {
    id: "routes/AnalysisSparc";
    page: "/analysis/sparc-galaxy-rotation-curves";
  };
  "routes/AnalysisSolarSystem.tsx": {
    id: "routes/AnalysisSolarSystem";
    page: "/analysis/solar-system";
  };
  "routes/curvature-response-model.tsx": {
    id: "routes/curvature-response-model";
    page: "/preprint/a-curvature-response-model-for-weak-field-gravity";
  };
  "routes/NonTrivialMarsBars.tsx": {
    id: "routes/NonTrivialMarsBars";
    page: "/non-trivial-mars-bars";
  };
  "routes/QuantumGravity.tsx": {
    id: "routes/QuantumGravity";
    page: "/notes/quantum-gravity-phase-resolution";
  };
  "routes/AnalysisBellToy.tsx": {
    id: "routes/AnalysisBellToy";
    page: "/notes/natural-mathematics-bell-toy";
  };
  "routes/regime-gate.tsx": {
    id: "routes/regime-gate";
    page: "/notes/regime-gate";
  };
  "routes/regime-gate-candles.tsx": {
    id: "routes/regime-gate-candles";
    page: "/notes/evaluation-protocol-for-progress-state-regime";
  };
  "routes/SwitchingQuadraticAtlas.tsx": {
    id: "routes/SwitchingQuadraticAtlas";
    page: "/notes/switching-quadratic-atlas-diagnostics";
  };
  "routes/GalaxyToy.tsx": {
    id: "routes/GalaxyToy";
    page: "/toy-galaxy";
  };
  "routes/UpdateGate.tsx": {
    id: "routes/UpdateGate";
    page: "/gate";
  };
  "routes/riemann.tsx": {
    id: "routes/riemann";
    page: "/rh";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/AnalysisSparc": typeof import("./app/routes/AnalysisSparc.tsx");
  "routes/AnalysisSolarSystem": typeof import("./app/routes/AnalysisSolarSystem.tsx");
  "routes/curvature-response-model": typeof import("./app/routes/curvature-response-model.tsx");
  "routes/NonTrivialMarsBars": typeof import("./app/routes/NonTrivialMarsBars.tsx");
  "routes/QuantumGravity": typeof import("./app/routes/QuantumGravity.tsx");
  "routes/AnalysisBellToy": typeof import("./app/routes/AnalysisBellToy.tsx");
  "routes/regime-gate": typeof import("./app/routes/regime-gate.tsx");
  "routes/regime-gate-candles": typeof import("./app/routes/regime-gate-candles.tsx");
  "routes/SwitchingQuadraticAtlas": typeof import("./app/routes/SwitchingQuadraticAtlas.tsx");
  "routes/GalaxyToy": typeof import("./app/routes/GalaxyToy.tsx");
  "routes/UpdateGate": typeof import("./app/routes/UpdateGate.tsx");
  "routes/riemann": typeof import("./app/routes/riemann.tsx");
};