// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/analysis/sparc-galaxy-rotation-curves": {
    params: {};
  };
  "/analysis/solar-system": {
    params: {};
  };
  "/preprint/a-curvature-response-model-for-weak-field-gravity": {
    params: {};
  };
  "/non-trivial-mars-bars": {
    params: {};
  };
  "/preprint/quantum-gravity-phase-resolution": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/analysis/sparc-galaxy-rotation-curves" | "/analysis/solar-system" | "/preprint/a-curvature-response-model-for-weak-field-gravity" | "/non-trivial-mars-bars" | "/preprint/quantum-gravity-phase-resolution";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/AnalysisSparc.tsx": {
    id: "routes/AnalysisSparc";
    page: "/analysis/sparc-galaxy-rotation-curves";
  };
  "routes/AnalysisSolarSystem.tsx": {
    id: "routes/AnalysisSolarSystem";
    page: "/analysis/solar-system";
  };
  "routes/curvature-response-model.tsx": {
    id: "routes/curvature-response-model";
    page: "/preprint/a-curvature-response-model-for-weak-field-gravity";
  };
  "routes/NonTrivialMarsBars.tsx": {
    id: "routes/NonTrivialMarsBars";
    page: "/non-trivial-mars-bars";
  };
  "routes/QuantumGravity.tsx": {
    id: "routes/QuantumGravity";
    page: "/preprint/quantum-gravity-phase-resolution";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/AnalysisSparc": typeof import("./app/routes/AnalysisSparc.tsx");
  "routes/AnalysisSolarSystem": typeof import("./app/routes/AnalysisSolarSystem.tsx");
  "routes/curvature-response-model": typeof import("./app/routes/curvature-response-model.tsx");
  "routes/NonTrivialMarsBars": typeof import("./app/routes/NonTrivialMarsBars.tsx");
  "routes/QuantumGravity": typeof import("./app/routes/QuantumGravity.tsx");
};